aboutUs/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path('', views.index, name="index"),
]

core/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views

from . forms import LoginForm

from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
    #  path('track-parcel/', views.track_parcel, name='track_parcel'),
]

packeting/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('services/', include("services.urls")),
    path('userProfile/', include("userProfile.urls")),
    path('aboutUs/', include("aboutUs.urls")),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "services"

urlpatterns = [
    path('', views.index, name="index"),
    path('select_service/<int:user_service_id>/', views.select_service, name="select_service"),
    path('details_view/<int:main_model_id>/', views.details_view, name="details_view"),
    path('details_view2/<int:main_model_id>', views.details_view2, name="details_view2"),
    path('details_summary/', views.details_summary, name="details_summary"),
    path('successful_order/', views.successful_order, name='successful_order'),
    path('order_destinations/', views.orderDestination, name='orderDestination'),
]

userProfile/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "userProfile"

urlpatterns = [
    path('', views.profile_showcase, name="profile_showcase"),
    path('profile/modify/', views.profile_modify, name="profile_modify"),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'   
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder':'Your username', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
		'placeholder':'Your email', 
		'class': 'w-full py-2 px-4 rounded-xl text-black'
	}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat your password', 
        'class': 'w-full py-2 px-4 rounded-xl text-black'
    }))

core/views.py
from django.shortcuts import render, redirect
from services.models import DeliveryService

from . forms import SignupForm

from django.core.mail import send_mail

from services.models import myParcelDetailsModel, ServicePacketingDeliveryMainModel

# Create your views here.
def index(request):

	return render(request, "core/index.html")


from django.template.loader import render_to_string

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            # Send email to the user
            subject = 'Welcome to Our Site!'
            message = render_to_string('core/signup_email.txt', {'user': user})
            user_email = form.cleaned_data.get('email')
            send_mail(subject, message, 'enisg1489@gmail.com', [user_email])

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})



# def track_parcel(request):
#     if request.method == 'POST':
#         parcel_name = request.POST.get('parcel_name')
        
#         try:
#             parcel_data = ServicePacketingDeliveryMainModel.objects.get(user=request.user, user_booking_data_model__parcels_details_data__parcel_contents=parcel_name)
#             destination = f"Destination: {parcel_data.delivery_data_model.delivery_details.delivery_full_name}"
#         except ServicePacketingDeliveryMainModel.DoesNotExist:
#             destination = "Parcel not found"
#         return render(request, 'core/base.html', {'destination': destination})
#     else:
#         return render(request, 'core/base.html')

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         <script src="https://cdn.tailwindcss.com"></script>

         <script src="https://cdn.jsdelivr.net/npm/kute.js@2.1.2/dist/kute.min.js"></script>

        <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
        <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

        <script src="https://api.opencagedata.com/geocode/v1/json?key=baa3dd40813940d4afb0837818a7f254"></script>

         <style>

            .carousel-item {
                    display: none;
            }
            .carousel-item.active {
                    display: flex;
            }

            .carousel-inner {
                transition: transform 0.5s ease-in-out;
            }


            .non-visible {
				opacity: 0;
				transition: all 2s;
				filter: blur(5px);
			}

			.show {
				opacity: 1;
				filter: blur(0);
			}

            .zoom-in {
                transform: scale(1);
                transition: transform 0.5s; 
            }

            .zoom-in.active {
                transform: scale(1.1);
            }

            .grow-on-hover {
                transition: transform 0.3s ease-in-out;
            }

            .grow-on-hover:hover {
                transform: scale(1.1); 
                cursor: pointer;
            }

            /* code for icons */

            .wave {
                width: 100%;
                overflow: hidden;
                line-height: 0;
            }

            .wave svg {
                position: relative;
                display: block;
                width: calc(103% + 1.3px);
                height: 262px;
            }

            .wave .shape-fill {
                fill: hsl(240, 3%, 6%);
            }


            @keyframes changeColor {
                    0%, 100% { fill: #BB004B; }
                    50% { fill: #E6E6FA; }
            }

            .color-changing-blob {
                animation: changeColor 10s ease-in-out infinite;
            }

            #services-div {
                background: rgb(0,0,0);
                background: linear-gradient(127deg, rgba(0,0,0,1) 0%, rgba(28,56,164,1) 0%, rgba(5,166,199,1) 100%);
            }

            /* code for stars display */
            svg {
                margin-bottom: 2em;
            }

                .rating__background {
                fill: #FFE372;
                stroke: red;
                stroke-width: 1;
                height: 100%;
                width: 100%;
                }

                .rating__value {
                fill: #FFB94B;
                height: 100%;
                }


        </style>


    </head>
    <body>

        <header class="text-white font-bold">
            <nav class="bg-black py-6 px-6 flex justify-center items-center border-b border-gray-400">
                <!-- <div class="flex justify-start">
                    <img class="w-28" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQf_1NXYK0kRAM4ls4fHQMHsC6AIunpJvHgOA&usqp=CAU" />
                </div> -->
                <div class="w-full flex flex-row justify-center items-center text-lg space-x-24 max-[1024px]:space-x-12 max-[1024px]:text-lg max-[768px]:text-sm max-[768px]:space-x-8 max-[768px]:w-full">
                    <a href="{% url 'core:index' %}" class="font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 max-[426px]:hidden">Home</a>
                    <a href="{% url 'about:index' %}" class="font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 max-[426px]:hidden">About us</a>
                    <a href="{% url 'userProfile:profile_showcase' %}" class="flex items-center p-2 font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 group max-[426px]:hidden">
                        <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                            <path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/>
                         </svg>
                        <span class="flex-1 ms-3 whitespace-nowrap">My Profile</span>
                    </a>
                    <a href="{% url 'services:index' %}" class="flex items-center p-2 font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 group max-[426px]:hidden">
                        <span class="flex-1 ms-3 whitespace-nowrap">My Services</span>
                    </a>

                    <span href="#" id="track_link" class="font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 max-[426px]:hidden">Track a parcel</span>
                    
                    <a href="{% url 'core:login' %}" class="font-semibold transition-all duration-300 ease-in-out hover:text-blue-500 max-[426px]:hidden max-[768px]:whitespace-nowrap">Log in</a>
                    <a href="{% url 'core:signup' %}" class="py-2 px-4 bg-[#800080] rounded-lg font-semibold transition-all duration-300 ease-in-out hover:bg-[#BF40BF] max-[426px]:hidden max-[768px]:whitespace-nowrap">Sign up</a>
                    <div class="flex flex-row items-center min-[426px]:hidden">
                        <button id="nav-btn" class="bg-transparent p-8">
                            <span class="bar bg-black block h-1 w-8 mb-1"></span>
                            <span class="bar bg-black block h-1 w-8 mb-1"></span>
                            <span class="bar bg-black block h-1 w-8"></span>
                        </button>
                    </div>
                </div>
            </nav>
        </header>


        {% block content %}

            <!-- <div id="sidebar" style="display: none;">
                <form id="track_form" method="post" action="{% url 'core:track_parcel' %}">
                    {% csrf_token %}
                    <label for="parcel_name">Enter Parcel Name:</label>
                    <input type="text" name="parcel_name" id="parcel_name">
                    <button type="submit">Track</button>
                </form>
                <p id="destination">{{ destination }}</p>
            </div> -->

        {% endblock %}

        <footer class="py-6 px-6 mt-12 bg-gray-600 text-white">
            <div class="flex flex-col justify-center gap-4">
                <div class="mx-2 w-full grid place-items-center">
                    <ul class="flex flex-row font-semibold text-lg max-[768px]:text-md max-[426px]:flex-col max-[426px]:text-lg max-[426px]:text-center">
                        <li class="mb-5 mx-6 max-[768px]:mx-4 text-hover-animation-footer hover:text-white">
                            
                        </li>
                        <li class="mb-5 mx-6 max-[768px]:mx-4 text-hover-animation-footer hover:text-white">Help {{ request.user.username}}</li>
                        <li class="mb-5 mx-6 max-[768px]:mx-4 text-hover-animation-footer hover:text-white">Lost & Found</li>
                        <li class="mb-5 mx-6 max-[768px]:mx-4 text-hover-animation-footer hover:text-white">Lockers</li>
                        <li class="mb-5 mx-6 max-[768px]:mx-4 text-hover-animation-footer hover:text-white">Lockers</li>
                    </ul>
                </div>

                <div class="flex flex-col justify-center items-center">
                    <p class="w-3/4 text-white text-md font-normal text-center my-4 max-[426px]:mb-8 text-sm w-4/5">On FareCompare, you will find cheap flights for domestic and international travel. Since airlines change flight prices constantly, sign up for Fare Alerts and let FareCompare’s travel search engine monitor airline ticket prices of all major airlines, so you’ll be first in line to get the cheapest tickets.</p>
                    <h5 class="text-center italic text-white text-sm mb-4">© Copyright 2006-2023 FareCompare.com. All rights reserved.</h5>
                </div>
            </div>
        </footer>

        <button id="scrollToTopButton" class="fixed bottom-8 right-8 bg-blue-500 text-white p-2 rounded-full cursor-pointer hidden">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18"></path>
            </svg>
        </button>

        <script src="{% static 'core/zoom.js' %}"></script>
        <script src="{% static 'core/scroll.js' %}"></script>
        <script src="{% static 'core/gradient.js' %}"></script>
        <script src="{% static 'core/scrollBtn.js' %}"></script>
        <script src="{% static 'aboutUs/carousel.js' %}"></script>
        <script src="{% static 'aboutUs/scale.js' %}"></script>
        <script src="{% static 'core/sidebar.js' %}" defer></script>


        <script src="{% static 'services/selectService.js' %}"></script>
        <script src="{% static 'services/map.js' %}"></script>

        

        <script>
            
            const tween = KUTE.fromTo(
              '#blob1',
              { path: '#blob1' },
              { path: '#blob2' },
              { repeat: 999, duration: 3000, yoyo: true }
            ).start();

          </script>

    </body>
</html>

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="bg-white dark:bg-gray-900">
    <div class="flex justify-center h-screen">
        <div class="hidden bg-cover lg:block lg:w-2/3" style="background-image: url(https://images.unsplash.com/photo-1616763355603-9755a640a287?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)">
            <div class="flex items-center h-full px-20 bg-gray-900 bg-opacity-40">
                <div>
                    <h2 class="text-6xl font-bold text-white">Join us</h2>
                    
                    <p class="text-xl max-w-xl mt-3 text-gray-300">Join us and reach the maximum possibilities in sending parcels and accepting them in real time.</p>
                </div>
            </div>
        </div>
        
        <div class="flex items-center w-full max-w-md px-6 mx-auto lg:w-2/6">
            <div class="flex-1">
                <div class="text-center">
                    <h2 class="text-4xl font-bold text-center text-gray-700 dark:text-white">Parcels</h2>
                    
                    <p class="mt-3 text-gray-500 dark:text-gray-300">Sign in to access your account</p>
                </div>

                <div class="mt-8">
                    <form method="post" action=".">
                        {% csrf_token %}
                        <div>
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Username</label>
                            {{ form.username }}
                            <!-- <input type="username" name="username" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" /> -->
                        </div>

                        <div class="mt-6">
                            <div>
                                <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200">Password</label>
                                {{ form.password }}
                                <!-- <a href="#" class="text-sm text-gray-400 focus:text-blue-500 hover:text-blue-500 hover:underline">Forgot password?</a> -->
                            </div>

                            <!-- <input type="password" name="password" id="password" placeholder="Your Password" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" /> -->
                        </div>

                        <div class="mt-6">
                            <button
                                class="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                                Sign in
                            </button>
                        </div>
                    </form>

                    <p class="mt-6 text-sm text-center text-gray-400">Don&#x27;t have an account yet? <a href="#" class="text-blue-500 focus:outline-none focus:underline hover:underline">Sign up</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/sidebar_template.html
{% extends "core/base.html" %}

{% block title %}{% endblock %}

{% block content %}

<div id="sidebar" style="display: none;">
    <form id="track_form" method="post" action="{% url 'core:track_parcel' %}">
        {% csrf_token %}
        <label for="parcel_name">Enter Parcel Name:</label>
        <input type="text" name="parcel_name" id="parcel_name">
        <button type="submit">Track</button>
    </form>
    <p id="destination">{{ destination }}</p>
</div>

{% endblock %}

core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="bg-white dark:bg-gray-900">
    <div class="flex justify-center h-screen">
        <div class="hidden bg-cover lg:block lg:w-2/3" style="background-image: url(https://images.unsplash.com/photo-1616763355603-9755a640a287?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80)">
            <div class="flex items-center h-full px-20 bg-gray-900 bg-opacity-40">
                <div>
                    <h2 class="text-6xl font-bold text-white">Join Us</h2>
                    
                    <p class="text-xl max-w-xl mt-3 text-gray-300">Join us and reach the maximum possibilities in sending parcels and accepting them in real time.</p>
                </div>
            </div>
        </div>
        
        <div class="flex items-center w-full max-w-md px-6 mx-auto lg:w-2/6">
            <div class="flex-1">
                <div class="text-center">
                    <h2 class="text-4xl font-bold text-center text-gray-700 dark:text-white">Parcels</h2>
                    
                    <p class="mt-3 text-gray-500 dark:text-gray-300">Sign up to create an account</p>
                </div>

                <div class="mt-8">
                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200" for="username">Username</label>
                            {{ form.username }}
                        </div>

                        <div class="mb-3">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200" for="email">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="mb-3">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200" for="password1">Password</label>
                            {{ form.password1 }}
                        </div>

                        <div class="mb-3">
                            <label class="block mb-2 text-sm text-gray-600 dark:text-gray-200" for="password2">Repeat Password</label>
                            {{ form.password2 }}
                        </div>

                        {% if form.errors or form.non_field_errors %}
                            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                {% for field in form %} 
                                    {{ field.errors }}
                                {% endfor %}

                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <button class="w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}