core/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views

from . forms import LoginForm

from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
    #  path('track-parcel/', views.track_parcel, name='track_parcel'),
]

packeting/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('services/', include("services.urls")),
    path('userProfile/', include("userProfile.urls")),
    path('aboutUs/', include("aboutUs.urls")),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "services"

urlpatterns = [
    path('', views.index, name="index"),
    path('select_service/<int:user_service_id>/', views.select_service, name="select_service"),
    path('details_view/<int:main_model_id>/', views.details_view, name="details_view"),
    path('details_view2/<int:main_model_id>', views.details_view2, name="details_view2"),
    path('details_summary/', views.details_summary, name="details_summary"),
    path('successful_order/', views.successful_order, name='successful_order'),
    path('order_destinations/', views.orderDestination, name='orderDestination'),
]

services/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ServiceModelForm, MyDetailsModelForm, ParcelDetailsModelForm, usersBookingDataForm, returnDetailsForm, deliveryDetailsForm, deliveryGuaranteeForm
from .models import SalesData,DeliveryService, myDetailsModel, returnDetailsModel, usersBookingData, deliveryDetailsData, ServiceUserModel, ServiceModel, ServicePacketingDeliveryMainModel
from django.contrib import messages
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.auth.models import User


from decimal import Decimal

@login_required
def index(request, user_service_id=0):
    if request.method == "POST":
        form = ServiceModelForm(request.POST)
        if form.is_valid():
            service_instance = form.save(commit=False)
            service_instance.user = request.user 
            service_instance.save()

            return redirect('services:select_service', user_service_id=0)
    else:
        form = ServiceModelForm()
    return render(request, "services/services.html", {'form': form})


# def select_service(request, user_service_id=None):
#     services = DeliveryService.objects.all()

#     if request.method == 'POST':
#         selected_service_id = request.POST.get('selected_service')
#         selected_service = DeliveryService.objects.get(id=selected_service_id)

#         user = request.user
#         user_service_instance = ServiceUserModel.objects.create(
#             user=user,
#             service_model_data=selected_service
#         )

#         return redirect('services:details_view',  main_model_id=user_service_instance.id)

#     return render(request, 'services/select_service.html', {'services': services})


def select_service(request, user_service_id=None):
    services = DeliveryService.objects.all()
    sales_data = SalesData.objects.select_related('selected_service_sale').last()

    if request.method == 'POST':
        selected_service_id = request.POST.get('selected_service')
        selected_service = DeliveryService.objects.get(id=selected_service_id)

        # Check if the sale has been applied to this service
        if not ServiceUserModel.objects.filter(user=request.user, service_model_data=selected_service, sale_applied=True).exists():
            # Calculate the price only if the sale hasn't been applied yet
            price = selected_service.price
            if sales_data and selected_service == sales_data.selected_service_sale:
                price = price - (price * sales_data.percentage_value / 100)
                selected_service.price = price
                selected_service.save()
                print(f"Discounted Price: {price}")

        # Create a new instance of ServiceUserModel
        user_service_instance = ServiceUserModel(
            user=request.user,
            service_model_data=selected_service,
            sale_applied=True
        )
        user_service_instance.save()

        return redirect('services:details_view', main_model_id=user_service_instance.id)

    sale_context = {}
    if sales_data:
        sale_context = {
            'sale_service_id': sales_data.selected_service_sale.id,
            'sales_data_percentage': sales_data.percentage_value
        }

    context = {
        'services': services,
        **sale_context
    }

    return render(request, 'services/select_service.html', context)

def details_view(request, main_model_id=None):
    service_instance = ServiceModel.objects.last()

    form1 = MyDetailsModelForm()
    form2 = ParcelDetailsModelForm()
    form3 = usersBookingDataForm()

    if request.method == "POST":
        form1 = MyDetailsModelForm(request.POST)
        form2 = ParcelDetailsModelForm(request.POST)
        form3 = usersBookingDataForm(request.POST, initial={'form1': form1, 'form2': form2})

        if form1.is_valid() and form2.is_valid() and form3.is_valid():
            my_details_instance = form1.save(commit=False)
            my_details_instance.user = request.user  
            my_details_instance.save()

            parcel_details_instance = form2.save()
            booking_data_instance = form3.save(commit=False)
            booking_data_instance.user = request.user
            booking_data_instance.user_details_data = my_details_instance
            booking_data_instance.parcels_details_data = parcel_details_instance
            booking_data_instance.save()

            main_model_instance = get_object_or_404(ServicePacketingDeliveryMainModel, pk=main_model_id)

            return redirect('services:details_view2', main_model_id=main_model_instance.id)
        else:
            for field, errors in form1.errors.items():
                for error in errors:
                    messages.error(request, f"Form 1 Error: {error}")

            for field, errors in form2.errors.items():
                for error in errors:
                    messages.error(request, f"Form 2 Error: {error}")

            for field, errors in form3.errors.items():
                for error in errors:
                    messages.error(request, f"Form 3 Error: {error}")

            return redirect('services:details_view2', user_service_id=user_service_id)

    return render(request, "services/details_view.html", {'form1': form1, 'form2': form2, 'form3': form3})

def details_view2(request, main_model_id=None):
    user = request.user
    user_info = myDetailsModel.objects.filter(user=user).last()
    booking_data_instance = usersBookingData.objects.filter(user=user).last()
    service_user_instance = ServiceUserModel.objects.filter(user=user).last()
    service_instance = ServiceModel.objects.filter(user=user).last()

    if request.method == "POST":
        form1_addr = returnDetailsForm(request.POST)
        form2_addr = deliveryDetailsForm(request.POST)
        form3_addr = deliveryGuaranteeForm(request.POST)

        if form1_addr.is_valid() and form2_addr.is_valid() and form3_addr.is_valid():
            return_details_instance = form1_addr.save()
            delivery_details_instance = form2_addr.save()
            guarantee_details_instance = form3_addr.save()

            delivery_data_instance = deliveryDetailsData.objects.create(
                user=user,
                return_details=return_details_instance,
                delivery_details=delivery_details_instance,
                guarantee_details=guarantee_details_instance
            )

            main_model_instance = ServicePacketingDeliveryMainModel.objects.create(
                user=user,
                user_booking_data_model=booking_data_instance,
                delivery_data_model=delivery_data_instance,
                service_data_model=service_user_instance,
                serviceModelInfo=service_instance
            )

            return redirect('services:details_summary')
    else:
        # Instantiate empty forms for GET requests
        form1_addr = returnDetailsForm()
        form2_addr = deliveryDetailsForm()
        form3_addr = deliveryGuaranteeForm()

    return render(request, "services/details_view2.html", {'form1_addr': form1_addr, 'form2_addr': form2_addr, 'form3_addr': form3_addr})

def details_summary(request):
    user = request.user
    recent_service_packeting_instance = ServicePacketingDeliveryMainModel.objects.filter(user=user).order_by('-id').first()

    if recent_service_packeting_instance:
        user_booking_data = recent_service_packeting_instance.user_booking_data_model
        delivery_data = recent_service_packeting_instance.delivery_data_model
        service_data = recent_service_packeting_instance.service_data_model
        serviceModelInfo = recent_service_packeting_instance.serviceModelInfo
    else:
        user_booking_data = None
        delivery_data = None
        service_data = None
        serviceModelInfo = None

    return render(request, "services/details_summary.html", {
        'user_booking_data': user_booking_data,
        'delivery_data': delivery_data,
        'service_data': service_data,
        'serviceModelInfo': serviceModelInfo,
    })



def orderDestination(request):
    current_user = request.user
    last_service_model = ServiceModel.objects.filter(user=current_user).last()
    sender_address = deliveryDetailsData.objects.filter(user=current_user).last()
    receiver_address = deliveryDetailsData.objects.filter(user=current_user).last()

    return render(request, 'services/orderDestination.html', {
        'last_service_model': last_service_model,
        'sender_address': sender_address,
        'receiver_address': receiver_address,
    })


def successful_order(request):
    user = request.user
    recent_service_packeting_instance = ServicePacketingDeliveryMainModel.objects.filter(user=user).order_by('-id').first()
    admin_user = User.objects.filter(is_staff=True, is_superuser=True).first()
    admin_email = admin_user.email

    if recent_service_packeting_instance:
        user_booking_data = recent_service_packeting_instance.user_booking_data_model
        delivery_data = recent_service_packeting_instance.delivery_data_model
        service_data = recent_service_packeting_instance.service_data_model
        serviceModelInfo = recent_service_packeting_instance.serviceModelInfo
    else:
        user_booking_data = None
        delivery_data = None
        service_data = None
        serviceModelInfo = None

    user_details = myDetailsModel.objects.filter(user=user).order_by('-id').first()
    recipient_email = user_details.email

    # Email for the client
    subject = 'Your service is booked!'
    message = render_to_string('services/success_email.txt', {
        'user_booking_data': user_booking_data,
        'delivery_data': delivery_data,
        'service_data': service_data,
        'serviceModelInfo': serviceModelInfo,
        'user': user,
    })

services/templates/services/details_view.html
{% extends "core/base.html" %}

{% block title %}Parcel Information{% endblock %}

{% block content %}

    {% include 'services/progress_bar.html' %}

    <div class="bg-gray-200">
        <div class="flex flex-row justify-center items-center space-x-8">
            
            <div class="w-1/2 flex flex-col justify-center items-center space-y-24">
                <form class="my-4" onsubmit="updateProgress('page1')" method="POST" id="form1details">
                    {% csrf_token %}
        
                    <div class="bg-white my-8 px-8 py-6 border-t-4 border-[#15537d]">
                        <div class="flex flex-col">
                            <h1 class="my-6 mb-10 self-start font-semibold text-3xl text-[#15537d]">My Details</h1>
                            <div class="flex flex-col justify-center items-center space-y-2">
                                <div class="flex flex-row justify-center items-center space-x-2 gap-2">
                                    <p class="text-gray-700 text-lg">Name: </p>
                                    <div>
                                        {{ form1.user_attr }}
                                    </div>
                                    <div>
                                        {{ form1.name }}
                                    </div>
                                    <div>
                                        {{ form1.surname }}
                                    </div>
                                </div>
                                <div class="flex flex-row items-center space-x-2">
                                    <p class="text-gray-700 text-lg">Email:</p>
                                    <div class="flex-grow"> <!-- Make email field take up remaining space -->
                                        {{ form1.email }}
                                    </div>
                                </div>

                            </div>
                            <div class="my-6"> 
                                <p class="my-6 text-base font-normal text-gray-700">You can change your mind at any time by opting out in your My Account area or clicking the unsubscribe link. 'We' means Parcel2Go.com, we'll never sell or share your information with anyone else. Click here to view our privacy policy.</p>
                            </div>
                            <div class="my-4">
                                <div class="bg-[#c5dfef] px-4 py-2 text-center text-md text-gray-700">Please note that the user data is used for the packeing so you may be supercharged.</div>
                            </div>
                        </div>
                    </div>

                    <div class="bg-white my-8 px-8 py-6 border-t-4 border-[#15537d]">
                        <div class="flex flex-col justify-center items-center space-y-4">
                            <h1 class="my-6 self-start font-semibold text-3xl text-[#15537d]">Parcel Details</h1>
                            <div class="flex flex-row justify-center items-center space-x-2 gap-2">
                                <p class="text-gray-700 text-lg">Parcel content: </p>
                                <div>
                                    {{ form2.parcel_contents }}
                                </div>
                                <!--Price should be herer-->
                            </div>
                            <div class="flex flex-row justify-center items-center space-x-2 mb-6">
                                <p>Length: </p>
                                {{ form2.length }}
                                <p>Height: </p>
                                {{ form2.height }}
                                <p>Width: </p>
                                {{ form2.width }}
                            </div>
                            <div class="bg-[#c5dfef] px-4 py-2 text-center text-md text-gray-700">Please note that under-declaring your parcel’s size or weight could result in additional surcharges</div>
                        </div>
                    </div>

                    <div class="bg-white my-8 px-8 py-6 border-t-4 border-[#15537d]">
                        <div class="flex flex-col justify-center items-center space-y-4">
                            <h1 class="text-3xl font-bold text-[#15537d]">£20.00 Parcel Protection on Your Evri Drop-off Delivery</h1>
                            <p class="font-semibold text-lg my-2 text-gray-700">Click here to find out more about fully protecting your parcel.</p>
                        </div>
                    </div>

                    <div class="bg-[#c5dfef] px-6 py-4 text-lg text-gray-700 my-8">
                        {{ form3 }} This parcel complies with the prohibited & restricted items list
                    </div>
        
                    <button type="submit"
                            class="font-bold my-4 text-lg rounded-xl px-8 py-2 outline-none border-none rounded-lg text-blue-700 bg-yellow-400 transition-all duration-300 ease-in-out hover:bg-yellow-500 hover:text-white max-[426px]:mt-8 max-[320px]:p-2 max-[320px]:px-4 whitespace-nowrap">Next Step
                    </button>
                </form>

            </div>

            <div class="w-1/3 flex flex-col justify-center items-center">
                <div class="w-full px-6 py-6 bg-[#c5dfef] flex flex-row justify-center items-center space-x-6">
                    <img class="w-32" src="https://www.parcel2go.com/logo/service/705.large" /> 
                    <h1 class="text-2xl font-semibold text-[#15537d]">Parcel to GOO</h1>
                </div>
                <div class="w-full px-6 py-6 bg-white">
                    <p class="text-base text-gray-700">If you’re looking for an easy and reliable service that doesn’t require anyone to be home to get their delivery, Evri Postable is for you. This service allows your courier to post items through the letterbox. Evri is a leading name in UK parcel delivery.

                        If you’re a retailer, a small business or just an individual looking to send letter-size items up to 1kg in weight, Evri Postable is just the service for you. To use the Evri service, drop your post off at any of the 5,000 Evri ParcelShops across the UK. Click here to find your nearest drop off location.Evri ParcelShop Postable
                        1 kg maximum weight
                        35cm x 23cm x 2.5cm maximum parcel size
                        Your postable delivery will be made within 3 working days.
                        Letterbox Postage
                        Evri Postable allows you to post a letter with ease, with no compromise on quality or reliability. If you do think you need letterbox postage, simply measure your item to see if it fits the letter requirements above.
                        
                        If you are looking for the cheapest way to send a small parcel that can fit through a standard letterbox, don’t hesitate to choose Evri Postable.</p>
                        <h1 class="text-xl text-[#15537d] my-4">Letter box </h1>
                        <p class="text-base text-gray-700" >Evri Postable allows you to post a letter with ease, with no compromise on quality or reliability. If you do think you need letterbox postage, simply measure your item to see if it fits the letter requirements above.

                            If you are looking for the cheapest way to send a small parcel that can fit through a standard letterbox, don’t hesitate to choose Evri Postable.</p>
                </div>
                <div class="w-full items-center ">
                    <button class="flex flex-row items-center justify-center w-full outline-none bg-transparent border-2 border-[#15537d] text-[#15537d] px-12 py-6 space-x-8 transition-all duration-300 ease-in-out hover:text-white hover:bg-[#15537d]">
                        <svg class="w-20" xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 121.86 122.88"><title>comment</title><path d="M30.28,110.09,49.37,91.78A3.84,3.84,0,0,1,52,90.72h60a2.15,2.15,0,0,0,2.16-2.16V9.82a2.16,2.16,0,0,0-.64-1.52A2.19,2.19,0,0,0,112,7.66H9.82A2.24,2.24,0,0,0,7.65,9.82V88.55a2.19,2.19,0,0,0,2.17,2.16H26.46a3.83,3.83,0,0,1,3.82,3.83v15.55ZM28.45,63.56a3.83,3.83,0,1,1,0-7.66h53a3.83,3.83,0,0,1,0,7.66Zm0-24.86a3.83,3.83,0,1,1,0-7.65h65a3.83,3.83,0,0,1,0,7.65ZM53.54,98.36,29.27,121.64a3.82,3.82,0,0,1-6.64-2.59V98.36H9.82A9.87,9.87,0,0,1,0,88.55V9.82A9.9,9.9,0,0,1,9.82,0H112a9.87,9.87,0,0,1,9.82,9.82V88.55A9.85,9.85,0,0,1,112,98.36Z"/></svg>
                        <div class="flex flex-col justify-center items-center space-y-2">
                            <h1 class="font-bold text-3xl whitespace-nowrap">Live Help</h1>
                            <p class=" font-semibold text-xl whitespace-nowrap">Talk to an operator</p>
                        </div>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script>
        updateProgress('page1');
    </script>
{% endblock %}
 

services/templates/services/orderDestination.html
{% extends "core/base.html" %}

{% block title %}Order destinations{% endblock %}

{% block content %}


<div class="w-full flex flex-row justify-center items-center">
    <div class="w-1/3 px-8 py-6 flex flex-col items-center justify-center space-y-24">
        <h1 class="text-black font-bold text-6xl">Addresses of the packeting delivery</h1>
        <p class="text-gray-700 text-lg font-normal">Our services take care managing the services and providing the delivery a safe and secure way. It is part of our policy and agreement to have the safety of the parcel on the first place and sent it anywhere on the world. Feel free to take a look at our page and see the services that we offer and also take a look at the delivery parcels.</p>
        <div class="flex flex-row justify-center items-center space-x-12">
            <button class="font-bold text-white text-md px-8 py-2 rounded-2xl bg-purple-500 transition-all duration-300 hover:bg-purple-700 focus:bg-purple-700">Shop now</button>
            <button class="flex gap-1 items-center group items-center border border-2 border-purple-500 text-purple-700 text-md px-8 py-2 rounded-2xl bg-white font-bold transition-all duration-300">Go back</button>
        </div>
    </div>


    <div id="container" class="w-2/3 bg-slate-200 px-0 py-6">

      <div id="container"></div>

        <div class="container my-24 mx-auto md:px-4">

            <section class="mb-32 text-center">
              <div class="py-12 md:px-2">
                <div class="container mx-auto xl:px-32">
                  <div class="grid items-center lg:grid-cols-2">
                    <div class="mb-12 md:mt-12 lg:mt-0 lg:mb-0">
                      <div
                        class="relative z-[1] block rounded-lg bg-white px-8 py-12 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] backdrop-blur-[30px] dark:bg-[hsla(0,0%,5%,0.7)] dark:shadow-black/20 md:px-12 lg:-mr-14">
                        <h2 class="mb-24 text-3xl font-bold">Order Destinations</h2>
                        <form>
                          <div class="flex flex-col justify-start items-center space-y-8 mb-10">
                            <div class="flex flex-col items-center space-y-2">
                                <div class="mb-6 flex flex-row space-x-8" data-te-input-wrapper-init>
                                    <h1 class="text-xl font-semibold text-gray-700">Packet sender</h1>
                                    <h1 class="text-xl font-bold text-black" id="departure">{{ last_service_model.sendFrom }}</h1>
                                </div>
    
                                <div class="mb-6 flex flex-row space-x-8" data-te-input-wrapper-init>
                                    <h1 class="text-lg font-normal text-gray-500">Address</h1>
                                    <h1 class="text-lg font-semibold text-gray-700">{{ sender_address.return_details.return_address}}</h1>
                                </div>
                            </div>
    
                            <div class="flex flex-col items-center space-y-2">
                                <div class="mb-6 flex flex-row space-x-8" data-te-input-wrapper-init>
                                    <h1 class="text-xl font-semibold text-gray-700">Packet Receiver</h1>
                                    <h1 class="text-xl font-bold text-black" id="destination">{{ last_service_model.sendTo }}</h1>
                                </div>
    
                                <div class="mb-6 flex flex-row space-x-8" data-te-input-wrapper-init>
                                    <h1 class="text-lg font-normal text-gray-500">Address</h1>
                                    <h1 class="text-lg font-semibold text-gray-700">{{ sender_address.delivery_details.delivery_address}}</h1>
                                </div>
                            </div>
    
                          </div>
                          <div class="relative mb-6" data-te-input-wrapper-init>
                          </div>
                          <!-- <div class="relative mb-6" data-te-input-wrapper-init>
                            <textarea
                              class="peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
                              id="exampleFormControlTextarea1"
                              rows="3"
                              placeholder="Your message"></textarea>
                            <label
                              for="exampleFormControlTextarea1"
                              class="pointer-events-none absolute top-0 left-3 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[1.6] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[0.9rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[0.9rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary"
                              >Message</label
                            >
                          </div> -->
                          <a href="{% url 'services:successful_order' %}">
                            <button
                                type="button"
                                data-te-ripple-init
                                data-te-ripple-color="light"
                                class="my-8 inline-block w-full rounded bg-primary px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-blue shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] dark:hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] lg:mb-0">
                                COUNTINUE
                            </button>
                          </a>
                        </form>
                      </div>
                    </div>
                    <div class="md:mb-12 lg:mb-0">
                      <div
                        class="relative h-[700px] rounded-lg shadow-lg dark:shadow-black/20">
                          <div id="map" class="absolute left-0 top-0 h-full w-full rounded-lg" allowfullscreen></div>
                      </div>
    
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <!-- Section: Design Block -->
          </div>
    
    </div>
    
</div>



{% endblock %}

services/templates/services/successful_order.html
<!-- track_order.html -->

{% extends "core/base.html" %}
{% block title %}Track Order{% endblock %}
{% block content %}
<div class="flex flex-col justify-center items-center w-full bg-green-200 p-4 my-4 rounded-md max-[426px]:p-6 max-[426px]:mt-8 max-[426px]:text-center">
    <h1 class="text-emerald-600 text-6xl font-bold my-8 max-[321px]:text-5xl">Your order is saved</h1>
    <p class="text-emerald-400 text-xl font-semibold my-8 max-[321px]:text-lg">The  <span class="text-emerald-600 animate-pulse">delivery</span> will take now place.</p>
    <a href="{% url 'services:index' %}" class="my-2 mb-8 outline-none border-none text-lg px-6 py-2 font-semibold text-white bg-teal-500 rounded-lg transition-all duration-300 ease-in-out hover:bg-teal-700">
        Go Back
    </a>
</div>
{% endblock %}